### ISSUE TITLE
Create Organization: Main button to perform this action doesnt always work

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#117]
## Expected Behaviour:

When clicking this button when Im on the /[dashboard](https://preview.virto.app/) page, [this url should be opened](https://preview.virto.app/onboarding)
![image](https://github.com/user-attachments/assets/535c360c-b397-43e1-b180-67f6ab4074dd)

## Current Behaviour:

Instead, I get this tooltip with a warning. Sometimes it works and sometimes it doesnt work, specially when we first open the app and click the button for the first time (on the second time it works just fine). If you wait a few seconds it works fine too.

<img width="1433" alt="Captura de pantalla 2024-10-08 a la(s) 12 09 12" src="https://github.com/user-attachments/assets/0e9abdbc-bb8d-4c49-9488-8e2fe1b9ca34">

**Comment by KatherineLopezPR** [comment]
1. Me pasa que cuando conecta mi wallet por primera vez a https://preview.virto.app/ el botón si me llevaba a la opción de "Crear tu organización".
2. Quise replicar la acción, pero me arrojo el error.

**Comment by ail3ngrimaldi** [comment]
Warning thrown by the console when the button does not work: Chain unavailable @b-avb
