### ISSUE TITLE
Warning notification doesnt disappear

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#118]
## Expected Behaviour:

When clicking the main "Create Organization" button, if something goes wrong a warning tooltip should appear for a few seconds, enough for the user (5 seconds max?) to read the warning message (that should be descriptive of the warning cause)

## Current Behaviour:

When something goes wrong with the main "Create Organization" button, a warning tooltip appears and it never leaves. This error doesnt happen always, sometimes it worked just fine.

![image](https://github.com/user-attachments/assets/31e914ca-a3f0-4603-96cc-b22e437dad8c)

**Comment by KatherineLopezPR** [comment]
1. Justo no me sucede este bug. Si muevo el cursor a otro botón el mensaje de error desaparece. También si recargo la página.

**Comment by ail3ngrimaldi** [comment]
I cant reproduce it so Ill put in on hold by now :)
