### ISSUE TITLE
Updating communities notification doesnt disappear

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#119]
## Expected Behaviour:

When opening the application, it loads all the communities registered and communicates it to the user through a tooltip. When the communities are fully loaded, the tooltip should disappear.

## Current Behaviour:

Even after the communities have loaded, the notification tooltip remains visible on the screen for a few extra seconds.

**Comment by KatherineLopezPR** [comment]
![WhatsApp Image 2024-10-09 at 5 33 55 PM](https://github.com/user-attachments/assets/9a212a62-3f24-40f0-a84c-88a3b7f09573)
