### ISSUE TITLE
Favorite option is not able to be removed from communities on /dashboard page

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#121]
## Expected Behaviour:

When a user adds a Community to Favourites it should be able to remove this state.

## Current Behaviour:

When you set a Community as favourite, if you are on the dashboard page, you cant remove this state.

**Comment by KatherineLopezPR** [comment]
Comportamiento similar!

**Comment by ail3ngrimaldi** [comment]
Not working on preview.virto.app but it does work on localhost and app.virto.dev

**Comment by ail3ngrimaldi** [comment]
Since it does work on app.virto.dev we are closing this issue.
