### ISSUE TITLE
Create Organization does not work

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#123]
## Expected Behaviour:

When we finish completing the form for the onboarding, an Organization should be created, or if our user do not has the permission to do it, we shouldnt be able to access to this section (either this, or an advice that we wont be able to create a community).

## Current Behaviour:
When trying to create an Organization the process is not able to finish and the error notification doesnt communicate the cause.

Possible causes could be:

- Lack of funds
- Lack of user permissions
- Wrong wallet address for members
- Connection to internet lost
- Connection to blockchain lost?

It should be properly listed so that the user can recover from this error and continue the action or call for support.

Console warnings during the process:

![image](https://github.com/user-attachments/assets/47ea02a5-e932-4fb3-9f79-5f5ce588be38)

![image](https://github.com/user-attachments/assets/e470ad82-bc8e-472b-9eb4-cce35b82a293)

**Comment by KatherineLopezPR** [comment]
Me gusta eso to pensando en la experiencia del usuario.

**Comment by ail3ngrimaldi** [comment]
More errors from console:

1. Access to fetch at 'https://bot-api.virto.app/room/create' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

        
2. POST https://bot-api.virto.app/room/create net::ERR_FAILED

**Comment by ail3ngrimaldi** [comment]
It worked on production so we are ready to close it.
