### ISSUE TITLE
Create Initiatives: Actions form is not so descriptive

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#124]
## Expected Behaviour:

When creating an Initiative the user should understand exactly what is the purpose of filling every input, so that it becomes more difficult to make any mistakes and create successful initiatives.

## Current Behaviour: 

When creating an Initiative, the second form is not very descriptive about:

- If it is mandatory to fill that part of the form .
- With what information should it be filled and why.

![image](https://github.com/user-attachments/assets/3d93c053-b084-4a4d-9408-58fe81b4cd18)

**Comment by KatherineLopezPR** [comment]
Me gusta la idea de mejor justo en la sección de acciones. Alguna manera que se derive de la sección de información. En la que cada campo tiene una descripción del por qué. 
![image](https://github.com/user-attachments/assets/694a29c1-18c5-42ab-afb7-8d5875f2a01c)
