### ISSUE TITLE
Create Initiative, Actions: Dropdown not clear

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#126]
## Expected Behaviour:

When you are about to create an Initiative, on the Action form -at this point Im not sure if the options should be exchangable- but as there is a dropdown and it has options I assume it is.

## Current Behaviour:

As the way the options are shown, it is not clear if the options are exchangable: 
![image](https://github.com/user-attachments/assets/324026f4-ddb4-49f5-83bc-948ad9afb821)

Plus, when you "choose" one of them, you cant know if it has been chosen correctly:

![image](https://github.com/user-attachments/assets/d5625918-247b-4922-b0f3-f3408395e0e9)

In the screenshot, I selected an option, but the input doesn't display the selection after closing the dropdown.

**Comment by KatherineLopezPR** [comment]
@ail3ngrimaldi Tengo el mismo comportamiento. Pero podríamos consultar con @b-avb @S0c5 La lógica de esto.
