### ISSUE TITLE
Create Initiative error notification doesnt disappear and is not descriptive

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#127]
## Expected Behaviour:

When the Creation of an Initiative fails, we expect that the error notification appears for a few seconds and tells us why the Initiative failed.

## Current Behaviour:

The message on the error notification doesnt help the user recover from the error and sometimes it stays for a longer time than expected.

![image](https://github.com/user-attachments/assets/e736fe65-6109-4668-bf9e-0ce5d108162c)

**Comment by KatherineLopezPR** [comment]
En mi caso si desaparecen, pero deberíamos revisar el porque sigue apareciendo el mensaje de error.
