### ISSUE TITLE
Create Initiative: Not possible.

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#128]
## Expected Behaviour:

When someone fills out the form to create an initiative, it's expected that after clicking the Continue button and signing the action, the initiative will be created.

## Current Behaviour: 

When clicking the Continue Button an error notification appears. The reason of the error is not clear. 

![image](https://github.com/user-attachments/assets/a281b1fb-f495-4a0a-be56-8b297e4d1440)

**Comment by ail3ngrimaldi** [comment]
More context: When writing down the description of the initiative, these errors appeared:

![Captura de pantalla 2024-10-11 a la(s) 11 03 29](https://github.com/user-attachments/assets/f478c8e7-ef9c-4d18-8c0e-fa0548a8c9ce)

**Comment by b-avb** [comment]
> More context: When writing down the description of the initiative, these errors appeared:
> 
> ![Captura de pantalla 2024-10-11 a la(s) 11 03 29](https://private-user-images.githubusercontent.com/63558201/375782535-f478c8e7-ef9c-4d18-8c0e-fa0548a8c9ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MzU2MTUsIm5iZiI6MTcyOTYzNTMxNSwicGF0aCI6Ii82MzU1ODIwMS8zNzU3ODI1MzUtZjQ3OGM4ZTctZWY5Yy00ZDE4LThjMGUtZmEwNTQ4YThjOWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDIyMTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZTA4NTg5NGRmOGZiNjEyMDQwMTEzM2JmNWRkOGZiYWRmMDhhYTk3NzdhZjIxMWYxZGQ2NzgxZjAzMTg2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HWuBKCV-J4_s-AgU_kIo0hR9uXGK59PiBXUIF5QD_HA)

Related with #137

**Comment by ail3ngrimaldi** [comment]
Closed by #149
