### ISSUE TITLE
Don't block loading communities for first time users

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-communities#181]
We need to improve our first interaction experience, new users without login land on the home with "your communities" which  stays loading communities for a while showing the placeholder cards, the problem is that the communities being loaded are not going to be shown to users until the load finishes and the "explore communities" card is shown.

We should immediately show the explore communities and create organization cards, we might still load the communities in the background or do it later when the user navigates the the *explore* section.

**Comment by ljuanto** [comment]
card is shown

**Comment by ljuanto** [comment]
card is shown
