### ISSUE TITLE
Virto team to offer infra + development services to kabocha in return for founding stake

### ISSUE THREAD

**Issue by monsieurbulb** [virto-network/virto-communities#56]
Propose Virto collective take over infra + maintenance and enable local governance of kabocha via krievo.

Virto to receive c 2% of newly minted supply - same as Brale. 

Tokens nominally valued at $0.1 with 69m fully diluted supply = implied market cap of $6.9m.

Tokens currently unlisted, but will have initial liquidity via LBP pallet on krievo and then launch on asset conversion pallet with KAB:KSM pair and KAB:dUSD pairs.

**Comment by olanod** [comment]
The Virto DAO's main business will be to offer infrastructure as a service to organizations in Kreivo with different subscription packages that enable different levels of scalability and influence in the core protocol. A deal for Virto to subsidize X months/years of the subscription service(which includes infra+maintenance+governance) in exchange for stake in Kabocha can happen but would need to be proposed and discussed in the Virto DAO.

**Comment by olanod** [comment]
Closing for now. We can create the initiative and have the discussion during Q3 in the virto.app once comments are enabled. 
To follow up on Kabocha as a satellite chain [here](https://github.com/virto-network/virto-node/issues/418)
For the LBP pallet [here](https://github.com/virto-network/virto-node/issues/419)
