### ISSUE TITLE
Create affiliate style marketing rewards scheme for collectives who integrate dUSD and drive economic adoption

### ISSUE THREAD

**Issue by monsieurbulb** [virto-network/virto-communities#62]
Use mix of on/off chain process to track + reward collectives integrating dUSD and driving economic engine of the network.

Use `system remark` and off-chain agreements for redistribution of fees.

Fees made up of dUSD (transaction fees) and KAB (network stake).

See MakerDAO example: 

https://x.com/RuneKek/status/1817973086693519771
https://forum.makerdao.com/t/improved-accessibility-reward/24744

> Integrators receive an Accessibility Reward Code. With the Accessibility Reward Code the Integrator can mark all NewStable balances that access the protocol through their frontends or infrastructure, and earn the Accessibility Reward on these balances.

> The distribution of Accessibility Reward Codes is managed by an Ecosystem Actor (A company) on behalf of SubDAOs. The Accessibility Reward Code Manager role is chosen through the SubDAOs own governance processes.

**Comment by olanod** [comment]
It seems it's mostly up to the interested party to monitor some behavior off-chain to then reward users. I imagine the Decent Partners DAO can deploy a smart contract to distribute rewards to collectives more easily.

I created https://github.com/virto-network/virto-node/issues/420 to follow up, it's a feature we can implement in payments pallet to have an on-chain automated mechanism to distribute such rewards.
