### ISSUE TITLE
Implement decaying categorical meritocracy as krievo governance framework

### ISSUE THREAD

**Issue by monsieurbulb** [virto-network/virto-communities#65]
Enable krievo membership NFTs to function with _decaying categorical meritocracy_ and to advance identity in DAOs based on an understanding that:

- Identity is non-transferable
- Identity is not fixed, but emergent
- Identity is context dependent

See https://app.t2.world/article/clp48u2of8539181ymcrc1zjioj by https://github.com/Swader 

Original twitter thread https://x.com/bitfalls/status/1620470410121986049

Related: [Kabocha seeds](https://gov.edgewa.re/discussion/6355-kabocha-seeds-outlining-the-evolving-concept-for-sovereign-identity-in-the-edgverse-and-beyond)

**Comment by olanod** [comment]
Created https://github.com/virto-network/virto-node/issues/422 to track the programmability of memberships, this kind of system can be implemented with a contract that has access to editing attributes of the NFT.
