### ISSUE TITLE
Add descriptive tags for Menu Icons (active ones)

### ISSUE THREAD

**Issue by ail3ngrimaldi** [virto-network/virto-communities#76]
This buttons should be labeled with a text indicating its action:

![image](https://github.com/user-attachments/assets/fda69748-cf5e-4a53-b308-6b92b5f8e833)

Suggestions:

- Inicio/Home
- Explorar/Explore
- ?

**Comment by olanod** [comment]
third one is a good question, I believe it implies creating a new community but that's not a frequent action, so it could be more for adding permanent quick access links to "the dock"(space after the separator) with different communities I'm member of or I want to follow, later it could also be used to pin rooms(e.g. regular chats or discussions?)

**Comment by ail3ngrimaldi** [comment]
![image](https://github.com/user-attachments/assets/2925b218-9854-4a0d-8ad9-37b28859de9b)

By now I've worked in this.
